language: node_js
node_js:
  - "7"

addons:
  code_climate:
    repo_token: 5cbadd6241aabeb2ac7441b1de7cf230a8bfac9b374ff2f3867b59852166d860

script: 
  - npm test -- --coverage
  - npm run flow -- check

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
