language: node_js
node_js:
  - "7"

addons:
  code_climate:
    repo_token: a256941e02d7a51acc01cf7f101d561d3f1315eef63dc1f284b6f068ad9c6da5

script: 
  - npm test -- --coverage
  - npm run flow -- check

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
